CREATE TABLE "book" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_isbn" int UNIQUE,
  "label_id" int,
  "book_title" varchar NOT NULL,
  "publish_id" int,
  "book_release_day" date,
  "book_price" int,
  "size_id" int NOT NULL,
  "book_explain" text,
  "book_add_time" timestamp NOT NULL,
  "book_update_time" timestamp NOT NULL
);

CREATE TABLE "book_label" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label_name" varchar UNIQUE NOT NULL,
  "label_phonic" varchar NOT NULL,
  "label_add_time" timestamp NOT NULL,
  "label_update_time" timestamp
);

CREATE TABLE "creator" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_name" varchar UNIQUE NOT NULL,
  "creator_name_phonic" varchar NOT NULL,
  "creator_add_time" timestamp NOT NULL,
  "creator_update_time" timestamp
);

CREATE TABLE "author_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int NOT NULL,
  "creator_id" int NOT NULL,
  "author_list_add_time" timestamp NOT NULL,
  "author_list_update_time" timestamp
);

CREATE TABLE "publish" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publish_name" varchar UNIQUE NOT NULL,
  "publish_name_phonic" varchar UNIQUE NOT NULL,
  "publish_add_time" timestamp NOT NULL,
  "publish_update_time" timestamp
);

CREATE TABLE "book_size" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "size_name" varchar UNIQUE NOT NULL,
  "size_add_time" timestamp NOT NULL,
  "size_update_time" timestamp
);

CREATE TABLE "series_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar UNIQUE NOT NULL,
  "status_add_time" timestamp NOT NULL,
  "status_update_time" timestamp
);

CREATE TABLE "series_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" int NOT NULL,
  "part_number" int NOT NULL,
  "book_id" int NOT NULL,
  "series_list_add_time" timestamp NOT NULL,
  "series_list_update_time" timestamp
);

CREATE TABLE "series_title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "series_name" varchar NOT NULL,
  "status_id" int NOT NULL,
  "series_title_add_time" timestamp NOT NULL,
  "series_title_update_time" timestamp
);

CREATE TABLE "tag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tag_name" varchar NOT NULL,
  "tag_add_time" timestamp NOT NULL,
  "tag_update_time" timestamp
);

CREATE TABLE "tag_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int NOT NULL,
  "tag_id" int NOT NULL,
  "tag_list_add_time" timestamp NOT NULL,
  "tag_list_update_time" timestamp
);

ALTER TABLE "book" ADD FOREIGN KEY ("label_id") REFERENCES "book_label" ("id");

ALTER TABLE "book" ADD FOREIGN KEY ("publish_id") REFERENCES "publish" ("id");

ALTER TABLE "book" ADD FOREIGN KEY ("size_id") REFERENCES "book_size" ("id");

ALTER TABLE "author_list" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");

ALTER TABLE "author_list" ADD FOREIGN KEY ("creator_id") REFERENCES "creator" ("id");

ALTER TABLE "series_list" ADD FOREIGN KEY ("title_id") REFERENCES "series_title" ("id");

ALTER TABLE "series_list" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");

ALTER TABLE "series_title" ADD FOREIGN KEY ("status_id") REFERENCES "series_status" ("id");

ALTER TABLE "tag_list" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");

ALTER TABLE "tag_list" ADD FOREIGN KEY ("tag_id") REFERENCES "tag" ("id");
