CREATE TABLE "book" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isbn" int,
  "label_id" int,
  "title" varchar,
  "publish_id" int,
  "release_day" datetime,
  "price" int,
  "size_id" int,
  "explain" text,
  "comment" text
);

CREATE TABLE "label" (
  "id" int PRIMARY KEY,
  "label_name" varchar,
  "label_phonic" varchar
);

CREATE TABLE "creator" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "author_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isbn" int,
  "creator_id" int
);

CREATE TABLE "publish" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "name_phonic" varchar
);

CREATE TABLE "size" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar
);

CREATE TABLE "series_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" int,
  "part_number" int,
  "book_id" int
);

CREATE TABLE "series_title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "series_name" varchar,
  "status_id" int
);

CREATE TABLE "tag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tag_name" varchar
);

CREATE TABLE "tag_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int,
  "tag_id" int
);

ALTER TABLE "book" ADD FOREIGN KEY ("label_id") REFERENCES "label" ("id");

ALTER TABLE "book" ADD FOREIGN KEY ("publish_id") REFERENCES "publish" ("id");

ALTER TABLE "book" ADD FOREIGN KEY ("size_id") REFERENCES "size" ("id");

ALTER TABLE "author_list" ADD FOREIGN KEY ("isbn") REFERENCES "book" ("id");

ALTER TABLE "author_list" ADD FOREIGN KEY ("creator_id") REFERENCES "creator" ("id");

ALTER TABLE "series_list" ADD FOREIGN KEY ("title_id") REFERENCES "series_title" ("id");

ALTER TABLE "series_list" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");

ALTER TABLE "series_title" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id");

ALTER TABLE "tag_list" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");

ALTER TABLE "tag_list" ADD FOREIGN KEY ("tag_id") REFERENCES "tag" ("id");
