name: Lint & Unit Test

on:
  push:
    branches-ignore:
      - main
      - release

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: go fmt & vet
        run: |
          go fmt ./...
          go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.5
          working-directory: ${{ env.WORKING_DIRECTORY }}

  unit-test:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: Run unit tests
        run: go test ./...
